"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ADD_VALUE_INPUT = 'ADD_VALUE_INPUT';
exports.ON_SUCCESSFUL_REQUEST = 'ON_SUCCESSFUL_REQUEST';
exports.ON_ERROR = 'ON_ERROR';
exports.ADD_DATA_WITH_CURRENT_PROPERTY = 'ADD_DATA_WITH_CURRENT_PROPERTY';
exports.CREATE_FAV_LIST_FROM_ASYNC_STORAGE = 'CREATE_FAV_LIST_FROM_ASYNC_STORAGE';
exports.ADD_FAVORITE = 'ADD_FAVORITE';
exports.REMOVE_FAVORITE = 'REMOVE_FAVORITE';
exports.REMOVE_CURRENT_FAVORITE = 'REMOVE_CURRENT_FAVORITE';
//# sourceMappingURL=types.js.map