export const ADD_VALUE_INPUT = 'ADD_VALUE_INPUT';
export const ON_SUCCESSFUL_REQUEST = 'ON_SUCCESSFUL_REQUEST';
export const ON_ERROR = 'ON_ERROR';
export const ADD_DATA_WITH_CURRENT_PROPERTY = 'ADD_DATA_WITH_CURRENT_PROPERTY';
